### ISSUE TITLE
Bug on slicing mesh

### ISSUE THREAD

**Issue by wainejr** [AeroSim-CFD/cfdmod#59]
The `slice_surface` is capable of generating an invalid triangle, with two points that are the same.
This generates an error for LNAS when trying to calculate the normals for the triangles.

## Reproduce

On branch `perf/proc` (or commit `eeacff73bc877b4b18667d73aca07260e2901adb`)

```yaml
shape_coefficient:
  "5x5":
    zoning: 
      global_zoning:
        x_intervals: [14.7237,  19.69489153,  24.66608305,  29.63727458,  34.6084661 ,  39.57965763,  44.55084915,  49.52204068,  54.4932322 ,  59.46442373,  64.43561525,  69.40680678,  74.37799831,  79.34918983,  84.32038136,  89.29157288,  94.26276441,  99.23395593, 104.20514746, 109.17633898, 114.14753051, 119.11872203, 124.08991356, 129.06110508, 134.03229661, 139.00348814, 143.97467966, 148.94587119, 153.91706271, 158.88825424, 163.85944576, 168.83063729, 173.80182881, 178.77302034, 183.74421186, 188.71540339, 193.68659492, 198.65778644, 203.62897797, 208.60016949, 213.57136102, 218.54255254, 223.51374407, 228.48493559, 233.45612712, 238.42731864, 243.39851017, 248.36970169, 253.34089322, 258.31208475, 263.28327627, 268.2544678 , 273.22565932, 278.19685085, 283.16804237, 288.1392339 , 293.11042542, 298.08161695, 303.05280847, 308.024]
        y_intervals: [0.9746, 5.99682222,  11.01904444,  16.04126667,  21.06348889,  26.08571111,  31.10793333,  36.13015556,  41.15237778,  46.1746    ,  51.19682222,  56.21904444,  61.24126667,  66.26348889,  71.28571111,  76.30793333,  81.33015556,  86.35237778,  91.3746    ,  96.39682222, 101.41904444, 106.44126667, 111.46348889, 116.48571111, 121.50793333, 126.53015556, 131.55237778, 136.5746    , 141.59682222, 146.61904444, 151.64126667, 156.66348889, 161.68571111, 166.70793333, 171.73015556, 176.75237778, 181.7746]
        z_intervals: [0, 6.1963, 12.3926]
      # Optional
      no_zoning: [] # Select the surfaces to ignore region mesh generation
      # Optional
      exclude: ["lanternins_refined", "m_000", "m_000_inside", "m_001", "m_001_inside", "m_002", "m_002_inside", "m_003", "m_003_inside", "m_004", "m_004_inside", "m_p_000", "m_p_000_inside", "m_p_001", "m_p_001_inside", "m_p_002", "m_p_002_inside", "m_p_003", "m_p_003_inside", "m_p_004", "m_p_004_inside", "p_xm_000_inside", "p_xp_000_inside", "p_ym_000_inside", "p_yp_000_inside"]
    statistics: ["mean", "mean_qs", "std", "xtr_max", "xtr_min"]
    sets:
      w_xm_000_full: ["p_xm_000", "w_xm_000"]
      w_xp_000_full: ["p_xp_000", "w_xp_000"]
      w_ym_000_full: ["p_ym_000", "w_ym_000"]
      w_yp_000_full: ["p_yp_000", "w_yp_000"]
    variables: ["Ce"]
    transformation:
      translation: [162.2262,95.3599,-628.2]
```

Lnas: `s3:aerosim-insight-dev-volume:/R01-MontoPirelli/G100/mesh/G100.merged.lnas`
Any file can be used as the time series, because it is not needed to reproduce the error (just make sure that the region processing is done before any time series processing, as it's already happening in the branch)

Command: 
```bash
poetry run python -m cfdmod.use_cases.pressure.shape --config output/debug/Ce_params.yaml --output output/debug_test/ --mesh output/debug/G100.merged.lnas --cp output/debug/time_series.h5 
# The yaml and mesh files were saved in the path of the command
```

## Observed behavior

For improved debugging, this code was added to `lnas/geometry.py` file on `_update_normals` function

```python
    def _update_normals(self):
        cross_prod = self._cross_prod()
        den = np.linalg.norm(cross_prod, axis=1)[:, np.newaxis]
        idxs_wrong = np.where(den == 0)[0]
        print("normals", idxs_wrong)
        for idx in idxs_wrong:
            print("wrong", self.triangle_vertices[idx])
        
        self._normals = cross_prod / den
        if np.isnan(self._normals).any():
            raise ValueError("Invalid normals generated, there is a NaN value")
```

Error and values on the terminal
![image](https://github.com/AeroSim-CFD/cfdmod/assets/102038240/2bf68658-7ce9-4af2-a5fd-4ee6c6630d6b)
The same can be reproduced using the old slicing method
![image](https://github.com/AeroSim-CFD/cfdmod/assets/102038240/b9112c01-8f71-4369-9d01-22308fbce8c2)

It's possible to see that a generated triangle has two vertices that are equal to each other.
Important to notice as well that precision np.float32 was used, a np.float64 could mask the error, but it would'nt make it go away. 

## Expected behavior

The `slice_surface` function should not generate invalid triangles. All triangles must have valid points (that is, not be 3 points in a line)

## Suspicions

I suspect that the `slice_triangle` function is responsible for that. You can add a checking for validation of triangle in it to assert that (as calculating the cross product and asserting it's not zero). The solution for the problem is to be proposed
